# Generated by Django 5.2.6 on 2025-09-24 23:04

import core.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المدرسة')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='رمز المدرسة')),
                ('address', models.TextField(blank=True, null=True, verbose_name='العنوان')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('principal_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم المدير')),
                ('academic_year_start', models.DateField(blank=True, null=True, verbose_name='بداية السنة الدراسية')),
                ('academic_year_end', models.DateField(blank=True, null=True, verbose_name='نهاية السنة الدراسية')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
            ],
            options={
                'verbose_name': 'مدرسة',
                'verbose_name_plural': 'المدارس',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='الاسم الأول')),
                ('last_name', models.CharField(max_length=50, verbose_name='اللقب')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('nid', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.MaxLengthValidator(11)], verbose_name='الرقم الوطني')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان السكن')),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='كود التسجيل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardian', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم المرتبط')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardians', to='core.school', verbose_name='المدرسة')),
            ],
            options={
                'verbose_name': 'ولي الأمر',
                'verbose_name_plural': 'أولياء الأمور',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GuardianStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('father', 'الأب'), ('mother', 'الأم'), ('brother', 'الأخ'), ('sister', 'الأخت'), ('grandparent', 'الجد/الجدة'), ('uncle', 'العم/الخال'), ('aunt', 'العمة/الخالة'), ('other', 'آخر')], default='father', max_length=20, verbose_name='العلاقة')),
                ('is_primary', models.BooleanField(default=False, verbose_name='ولي أساسي؟')),
                ('is_emergency_contact', models.BooleanField(default=False, verbose_name='جهة اتصال طارئة؟')),
                ('can_pickup', models.BooleanField(default=True, verbose_name='يمكنه استلام الطالب؟')),
                ('can_receive_notifications', models.BooleanField(default=True, verbose_name='يستقبل الإشعارات؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.guardian', verbose_name='الولي')),
            ],
            options={
                'verbose_name': 'صلة ولي الأمر بالطالب',
                'verbose_name_plural': 'صلات الأولياء بالطلبة',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم الصف')),
                ('level', models.PositiveIntegerField(verbose_name='المستوى')),
                ('grade_type', models.CharField(choices=[('kindergarten', 'روضة'), ('primary', 'ابتدائي'), ('middle', 'إعدادي'), ('secondary', 'ثانوي')], max_length=20, verbose_name='نوع المرحلة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='core.school', verbose_name='المدرسة')),
            ],
            options={
                'verbose_name': 'صف دراسي',
                'verbose_name_plural': 'الصفوف الدراسية',
                'ordering': ['grade_type', 'level'],
                'unique_together': {('school', 'level', 'grade_type')},
            },
        ),
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='السنة الدراسية')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('is_current', models.BooleanField(default=False, verbose_name='السنة الحالية؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_years', to='core.school', verbose_name='المدرسة')),
            ],
            options={
                'verbose_name': 'سنة دراسية',
                'verbose_name_plural': 'السنوات الدراسية',
                'ordering': ['-start_date'],
                'unique_together': {('school', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم الفصل')),
                ('section', models.CharField(blank=True, max_length=10, null=True, verbose_name='الشعبة')),
                ('capacity', models.PositiveIntegerField(default=30, verbose_name='السعة القصوى')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='core.academicyear', verbose_name='السنة الدراسية')),
                ('class_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_classes', to=settings.AUTH_USER_MODEL, verbose_name='المعلم المسؤول')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='core.grade', verbose_name='الصف')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='core.school', verbose_name='المدرسة')),
            ],
            options={
                'verbose_name': 'فصل دراسي',
                'verbose_name_plural': 'الفصول الدراسية',
                'ordering': ['grade__level', 'name'],
                'unique_together': {('school', 'grade', 'academic_year', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, verbose_name='الرقم الجامعي')),
                ('first_name', models.CharField(max_length=50, verbose_name='الاسم الأول')),
                ('second_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='اسم الأب')),
                ('third_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='اسم الجد')),
                ('fourth_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='اسم جد الأب')),
                ('last_name', models.CharField(max_length=50, verbose_name='اللقب')),
                ('full_name', models.CharField(editable=False, max_length=255, null=True, verbose_name='الاسم الكامل')),
                ('sex', models.CharField(choices=[('male', 'ذكر'), ('female', 'أنثى')], max_length=10, verbose_name='الجنس')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('place_of_birth', models.CharField(blank=True, max_length=255, null=True, verbose_name='مكان الميلاد')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='رقم الهاتف')),
                ('alternative_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='رقم هاتف بديل')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('nid', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.MaxLengthValidator(11)], verbose_name='الرقم الوطني')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان السكن')),
                ('enrollment_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التسجيل')),
                ('graduation_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التخرج')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('current_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.schoolclass', verbose_name='الفصل الحالي')),
                ('guardians', models.ManyToManyField(related_name='students', through='core.GuardianStudent', to='core.guardian', verbose_name='الأولياء')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='core.school', verbose_name='المدرسة')),
            ],
            options={
                'verbose_name': 'طالب',
                'verbose_name_plural': 'الطلبة',
                'ordering': ['last_name', 'first_name'],
                'unique_together': {('school', 'student_id')},
            },
        ),
        migrations.AddField(
            model_name='guardianstudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student', verbose_name='الطالب'),
        ),
        migrations.AddField(
            model_name='guardian',
            name='selected_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_for_guardians', to='core.student', verbose_name='الطالب المختار'),
        ),
        migrations.CreateModel(
            name='StudentTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='العنوان')),
                ('note', models.TextField(blank=True, verbose_name='المحتوى')),
                ('content_type', models.CharField(choices=[('note', 'ملاحظة'), ('achievement', 'إنجاز'), ('behavior', 'سلوك'), ('health', 'صحة'), ('academic', 'أكاديمي'), ('attendance', 'حضور'), ('other', 'آخر')], default='note', max_length=20, verbose_name='نوع المحتوى')),
                ('is_visible_to_guardian', models.BooleanField(default=True, verbose_name='مرئي لولي الأمر؟')),
                ('is_visible_to_student', models.BooleanField(default=False, verbose_name='مرئي للطالب؟')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='مثبّت؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_timeline_notes', to=settings.AUTH_USER_MODEL, verbose_name='أضيفت بواسطة')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='core.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'ملاحظة الطالب',
                'verbose_name_plural': 'ملاحظات الطلبة',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentTimelineAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=core.models.timeline_upload_path, verbose_name='الملف')),
                ('is_image', models.BooleanField(default=False, verbose_name='صورة؟')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='حجم الملف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('timeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.studenttimeline', verbose_name='المحتوى')),
            ],
            options={
                'verbose_name': 'مرفق ملاحظة',
                'verbose_name_plural': 'مرفقات الملاحظات',
            },
        ),
        migrations.AddIndex(
            model_name='guardianstudent',
            index=models.Index(fields=['guardian', 'student'], name='core_guardi_guardia_962308_idx'),
        ),
        migrations.AddIndex(
            model_name='guardianstudent',
            index=models.Index(fields=['student', 'is_primary'], name='core_guardi_student_62ef36_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='guardianstudent',
            unique_together={('guardian', 'student')},
        ),
        migrations.AddIndex(
            model_name='studenttimeline',
            index=models.Index(fields=['student', '-created_at'], name='core_studen_student_3155aa_idx'),
        ),
        migrations.AddIndex(
            model_name='studenttimeline',
            index=models.Index(fields=['created_by', '-created_at'], name='core_studen_created_44d9aa_idx'),
        ),
    ]
