# Generated by Django 4.2.7 on 2025-08-09 13:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=50, verbose_name="الاسم الأول"),
                ),
                (
                    "second_name",
                    models.CharField(max_length=50, null=True, verbose_name="اسم الأب"),
                ),
                (
                    "third_name",
                    models.CharField(max_length=50, null=True, verbose_name="اسم الجد"),
                ),
                (
                    "fourth_name",
                    models.CharField(
                        max_length=50, null=True, verbose_name="اسم جد الأب"
                    ),
                ),
                ("last_name", models.CharField(max_length=50, verbose_name="اللقب")),
                (
                    "full_name",
                    models.CharField(
                        editable=False,
                        max_length=255,
                        null=True,
                        verbose_name="الاسم الكامل",
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        choices=[("male", "ذكر"), ("female", "أنثى")],
                        max_length=10,
                        verbose_name="الجنس",
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(null=True, verbose_name="تاريخ الميلاد"),
                ),
                (
                    "place_of_birth",
                    models.CharField(
                        max_length=255, null=True, verbose_name="مكان الميلاد"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="رقم الهاتف"
                    ),
                ),
                (
                    "alternative_phone",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="رقم هاتف بديل",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="البريد الإلكتروني",
                    ),
                ),
                (
                    "nid",
                    models.CharField(
                        blank=True,
                        max_length=11,
                        null=True,
                        validators=[
                            django.core.validators.MinLengthValidator(11),
                            django.core.validators.MaxLengthValidator(11),
                        ],
                        verbose_name="الرقم الوطني",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="عنوان السكن",
                    ),
                ),
            ],
        ),
    ]
