# Generated by Django 5.2.6 on 2025-11-02 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='schools/logos/%Y/%m/', verbose_name='شعار المدرسة'),
        ),
    ]
