# Generated by Django 4.2.7 on 2025-08-09 15:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Guardian",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=50, verbose_name="الاسم الأول"),
                ),
                ("last_name", models.CharField(max_length=50, verbose_name="اللقب")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="الهاتف"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="البريد الإلكتروني",
                    ),
                ),
                (
                    "nid",
                    models.CharField(
                        blank=True,
                        max_length=11,
                        null=True,
                        validators=[
                            django.core.validators.MinLengthValidator(11),
                            django.core.validators.MaxLengthValidator(11),
                        ],
                        verbose_name="الرقم الوطني",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="عنوان السكن",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التعديل"),
                ),
            ],
            options={
                "verbose_name": "ولي الأمر",
                "verbose_name_plural": "أولياء الأمور",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="student",
            options={
                "ordering": ["last_name", "first_name"],
                "verbose_name": "طالب",
                "verbose_name_plural": "الطلبة",
            },
        ),
        migrations.AddField(
            model_name="student",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="تاريخ الإنشاء",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="student",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="تاريخ التعديل"),
        ),
        migrations.CreateModel(
            name="GuardianStudent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("father", "الأب"),
                            ("mother", "الأم"),
                            ("brother", "الأخ"),
                            ("sister", "الأخت"),
                            ("grandparent", "الجد/الجدة"),
                            ("other", "آخر"),
                        ],
                        default="father",
                        max_length=20,
                        verbose_name="العلاقة",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="ولي أساسي؟"),
                ),
                (
                    "guardian",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.guardian",
                        verbose_name="الولي",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.student",
                        verbose_name="الطالب",
                    ),
                ),
            ],
            options={
                "verbose_name": "صلة ولي الأمر بالطالب",
                "verbose_name_plural": "صلات الأولياء بالطلبة",
            },
        ),
        migrations.AddField(
            model_name="student",
            name="guardians",
            field=models.ManyToManyField(
                related_name="students",
                through="core.GuardianStudent",
                to="core.guardian",
                verbose_name="الأولياء",
            ),
        ),
        migrations.AddIndex(
            model_name="guardianstudent",
            index=models.Index(
                fields=["guardian", "student"], name="core_guardi_guardia_962308_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="guardianstudent",
            index=models.Index(
                fields=["student", "is_primary"], name="core_guardi_student_62ef36_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="guardianstudent",
            unique_together={("guardian", "student")},
        ),
    ]
