# Generated by Django 4.2.7 on 2025-08-23 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0002_guardian_alter_student_options_student_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="guardian",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="guardian",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المستخدم المرتبط",
            ),
        ),
    ]
