# Generated by Django 5.2.6 on 2025-11-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_school_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolclass',
            name='section',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='المبنى'),
        ),
    ]
