# Generated by Django 4.2.7 on 2025-08-23 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_guardian_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="guardian",
            name="selected_student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="selected_for_guardians",
                to="core.student",
                verbose_name="الطالب المختار",
            ),
        ),
    ]
