# Generated by Django 4.2.7 on 2025-09-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_guardian_selected_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="guardian",
            name="code",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="كود التسجيل",
            ),
        ),
    ]
