# Generated by Django 4.2.7 on 2025-09-20 16:16

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0005_guardian_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentTimeline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="العنوان"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="الملاحظة")),
                (
                    "is_pinned",
                    models.BooleanField(default=False, verbose_name="مثبّت؟"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student_timeline_notes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="أضيفت بواسطة",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline",
                        to="core.student",
                        verbose_name="الطالب",
                    ),
                ),
            ],
            options={
                "verbose_name": "ملاحظة الطالب",
                "verbose_name_plural": "ملاحظات الطلبة",
                "ordering": ["-is_pinned", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StudentTimelineAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=core.models.timeline_upload_path, verbose_name="الملف"
                    ),
                ),
                ("is_image", models.BooleanField(default=False, verbose_name="صورة؟")),
                (
                    "timeline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="core.studenttimeline",
                        verbose_name="الملاحظة",
                    ),
                ),
            ],
            options={
                "verbose_name": "مرفق ملاحظة",
                "verbose_name_plural": "مرفقات الملاحظات",
            },
        ),
    ]
