# Generated by Django 5.2.6 on 2025-09-24 23:04

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, verbose_name='الرقم الوظيفي')),
                ('position', models.CharField(choices=[('principal', 'مدير المدرسة'), ('vice_principal', 'نائب المدير'), ('admin', 'إداري'), ('accountant', 'محاسب'), ('librarian', 'أمين مكتبة'), ('nurse', 'ممرض'), ('security', 'أمن'), ('cleaner', 'نظافة'), ('other', 'أخرى')], max_length=50, verbose_name='المنصب')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='القسم')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التوظيف')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='الراتب')),
                ('can_manage_students', models.BooleanField(default=False, verbose_name='يمكنه إدارة الطلاب')),
                ('can_manage_teachers', models.BooleanField(default=False, verbose_name='يمكنه إدارة المعلمين')),
                ('can_view_reports', models.BooleanField(default=True, verbose_name='يمكنه عرض التقارير')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'ملف موظف',
                'verbose_name_plural': 'ملفات الموظفين',
            },
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, verbose_name='الرقم الوظيفي')),
                ('subject', models.CharField(blank=True, max_length=100, null=True, verbose_name='المادة المتخصصة')),
                ('qualification', models.CharField(blank=True, max_length=200, null=True, verbose_name='المؤهل العلمي')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='سنوات الخبرة')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التوظيف')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='الراتب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_class_teacher', models.BooleanField(default=False, verbose_name='معلم فصل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'ملف معلم',
                'verbose_name_plural': 'ملفات المعلمين',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[('student', 'طالب'), ('guardian', 'ولي أمر'), ('teacher', 'معلم'), ('employee', 'موظف'), ('admin', 'مدير'), ('supervisor', 'مشرف')], default='employee', max_length=20, verbose_name='نوع المستخدم')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/', verbose_name='الصورة الشخصية')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='رقم الهاتف')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تم التحقق منه')),
                ('last_activity', models.DateTimeField(blank=True, null=True, verbose_name='آخر نشاط')),
                ('language', models.CharField(choices=[('ar', 'العربية'), ('en', 'English')], default='ar', max_length=10, verbose_name='اللغة')),
                ('theme', models.CharField(choices=[('light', 'فاتح'), ('dark', 'داكن')], default='light', max_length=10, verbose_name='المظهر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'مستخدم',
                'verbose_name_plural': 'المستخدمون',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
