# Generated by Django 4.2.7 on 2025-08-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="type",
            field=models.CharField(
                choices=[("student", "Student"), ("guardian", "Guardian")],
                default="employee",
                max_length=10,
                verbose_name="نوع المستخدم",
            ),
        ),
    ]
