# Generated by Django 5.2.6 on 2025-09-24 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_frequency', models.CharField(blank=True, choices=[('weekly', 'أسبوعي'), ('monthly', 'شهري'), ('quarterly', 'كل 3 أشهر'), ('yearly', 'سنوي')], default='monthly', max_length=20, null=True, verbose_name='التكرار الافتراضي')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='الاسم')),
                ('type', models.CharField(choices=[('food', 'طعام')], default='food', max_length=16, verbose_name='النوع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL, verbose_name='منشئ النموذج')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_templates', to=settings.AUTH_USER_MODEL, verbose_name='محدث النموذج')),
            ],
            options={
                'verbose_name': 'نموذج التذكرة',
                'verbose_name_plural': 'نماذج التذاكر',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='core.guardian', verbose_name='الولي')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='core.student', verbose_name='الطالب')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='survey.template', verbose_name='النموذج')),
            ],
            options={
                'verbose_name': 'رد نموذج البلاغ',
                'verbose_name_plural': 'ردود نماذج البلاغات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplateField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=16, unique=True, verbose_name='المفتاح')),
                ('name', models.CharField(max_length=255, verbose_name='عنوان الحقل')),
                ('type', models.CharField(choices=[('text', 'نص'), ('textarea', 'نص طويل'), ('number', 'رقم'), ('select', 'قائمة منسدلة'), ('checkbox', 'متعدد الخيارات'), ('radio', 'خيار واحد'), ('date', 'تاريخ')], default='text', max_length=10, verbose_name='النوع')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('is_public', models.BooleanField(default=True, verbose_name='مرئي للمواطن؟')),
                ('is_required', models.BooleanField(default=False, verbose_name='حقل إجباري؟')),
                ('is_multiple', models.BooleanField(default=False, verbose_name='متعدد الإدخالات؟')),
                ('value', models.JSONField(blank=True, default=None, null=True, verbose_name='القيم')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_template_fields', to=settings.AUTH_USER_MODEL, verbose_name='منشئ الحقل')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='survey.template', verbose_name='النموذج')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_template_fields', to=settings.AUTH_USER_MODEL, verbose_name='محدث الحقل')),
            ],
            options={
                'verbose_name': 'حقل نموذج البلاغ',
                'verbose_name_plural': 'حقول نماذج البلاغات',
                'ordering': ['template', 'order'],
            },
        ),
        migrations.AddField(
            model_name='template',
            name='parent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_form', to='survey.templatefield', verbose_name='حقل النموذج'),
        ),
        migrations.CreateModel(
            name='AdditionalField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('text', 'نص'), ('textarea', 'نص طويل'), ('number', 'رقم'), ('select', 'قائمة منسدلة'), ('checkbox', 'متعدد الخيارات'), ('radio', 'خيار واحد'), ('date', 'تاريخ')], default='text', max_length=10, verbose_name='النوع')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم')),
                ('value', models.JSONField(blank=True, default=None, null=True, verbose_name='القيمة')),
                ('row', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_additional_fields', to=settings.AUTH_USER_MODEL, verbose_name='منشئ الحقل')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_fields', to='survey.additionalfield', verbose_name='حقل النموذج')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_additional_fields', to=settings.AUTH_USER_MODEL, verbose_name='محدث الحقل')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='survey.response', verbose_name='الرد')),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to='survey.templatefield', verbose_name='الحقل')),
            ],
            options={
                'ordering': ['row'],
            },
        ),
        migrations.AddIndex(
            model_name='response',
            index=models.Index(fields=['template', 'guardian', '-created_at'], name='survey_resp_templat_9bed15_idx'),
        ),
    ]
