# Generated by Django 4.2.7 on 2025-08-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="default_frequency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("weekly", "أسبوعي"),
                    ("monthly", "شهري"),
                    ("quarterly", "كل 3 أشهر"),
                    ("yearly", "سنوي"),
                    ("every_n_days", "كل عدد أيام محدد"),
                ],
                default="monthly",
                max_length=20,
                null=True,
                verbose_name="التكرار الافتراضي",
            ),
        ),
        migrations.AlterField(
            model_name="additionalfield",
            name="type",
            field=models.CharField(
                choices=[
                    ("text", "نص"),
                    ("textarea", "نص طويل"),
                    ("number", "رقم"),
                    ("select", "قائمة منسدلة"),
                    ("checkbox", "متعدد الخيارات"),
                    ("radio", "خيار واحد"),
                    ("date", "تاريخ"),
                ],
                default="text",
                max_length=10,
                verbose_name="النوع",
            ),
        ),
        migrations.AlterField(
            model_name="templatefield",
            name="type",
            field=models.CharField(
                choices=[
                    ("text", "نص"),
                    ("textarea", "نص طويل"),
                    ("number", "رقم"),
                    ("select", "قائمة منسدلة"),
                    ("checkbox", "متعدد الخيارات"),
                    ("radio", "خيار واحد"),
                    ("date", "تاريخ"),
                ],
                default="text",
                max_length=10,
                verbose_name="النوع",
            ),
        ),
    ]
