# Generated by Django 5.2.6 on 2025-10-04 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='school',
            field=models.ForeignKey(blank=True, help_text='إذا كان فارغاً، فهو متاح لجميع المدارس', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='core.school', verbose_name='المدرسة'),
        ),
    ]
