# Generated by Django 4.2.7 on 2025-08-23 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_guardian_user"),
        ("survey", "0002_template_default_frequency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="template",
            name="default_frequency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("weekly", "أسبوعي"),
                    ("monthly", "شهري"),
                    ("quarterly", "كل 3 أشهر"),
                    ("yearly", "سنوي"),
                ],
                default="monthly",
                max_length=20,
                null=True,
                verbose_name="التكرار الافتراضي",
            ),
        ),
        migrations.CreateModel(
            name="Response",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التعديل"),
                ),
                (
                    "guardian",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="core.guardian",
                        verbose_name="الولي",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="survey.template",
                        verbose_name="النموذج",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="additionalfield",
            name="response",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fields",
                to="survey.response",
                verbose_name="الرد",
            ),
            preserve_default=False,
        ),
    ]
