# Generated by Django 5.2.6 on 2025-11-09 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_schoolclass_section'),
        ('survey', '0002_template_school'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='response',
            name='survey_resp_templat_9bed15_idx',
        ),
        migrations.RemoveField(
            model_name='template',
            name='default_frequency',
        ),
        migrations.AddField(
            model_name='response',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_responses', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AddField(
            model_name='template',
            name='grades',
            field=models.ManyToManyField(blank=True, help_text='اختر الصفوف المستهدفة (فقط لاستطلاعات أولياء الأمور). اتركه فارغاً لجميع الصفوف.', related_name='templates', to='core.grade', verbose_name='الصفوف'),
        ),
        migrations.AddField(
            model_name='template',
            name='is_builtin',
            field=models.BooleanField(default=False, help_text='النماذج المدمجة من المسؤول متاحة لجميع المدارس. النماذج المخصصة خاصة بمدرسة واحدة فقط.', verbose_name='نموذج مدمج'),
        ),
        migrations.AddField(
            model_name='template',
            name='send_frequency',
            field=models.CharField(choices=[('once', 'مرة واحدة (يدوي)'), ('weekly', 'أسبوعي'), ('monthly', 'شهري'), ('quarterly', 'كل 3 أشهر'), ('yearly', 'سنوي')], default='monthly', help_text='كم مرة سيتم إرسال هذا الاستطلاع؟', max_length=20, verbose_name='تكرار الإرسال'),
        ),
        migrations.AddField(
            model_name='template',
            name='target_audience',
            field=models.CharField(choices=[('guardians', 'أولياء الأمور'), ('teachers', 'المعلمون'), ('employees', 'الموظفون'), ('all', 'الجميع')], default='guardians', help_text='لمن هذا الاستطلاع؟', max_length=20, verbose_name='الجمهور المستهدف'),
        ),
        migrations.AlterField(
            model_name='response',
            name='guardian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_responses', to='core.guardian', verbose_name='الولي (قديم)'),
        ),
        migrations.AlterField(
            model_name='response',
            name='student',
            field=models.ForeignKey(blank=True, help_text='الطالب المعني (فقط لاستطلاعات أولياء الأمور)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='core.student', verbose_name='الطالب'),
        ),
        migrations.AddIndex(
            model_name='response',
            index=models.Index(fields=['template', 'user', '-created_at'], name='survey_resp_templat_d7fe88_idx'),
        ),
        migrations.AddIndex(
            model_name='response',
            index=models.Index(fields=['template', 'student', '-created_at'], name='survey_resp_templat_044a62_idx'),
        ),
    ]
