# Generated by Django 5.2.6 on 2025-11-09 19:38

from django.db import migrations


def migrate_guardian_to_user(apps, schema_editor):
    """
    Data migration to copy guardian.user to Response.user field
    for all existing Response records
    """
    Response = apps.get_model('survey', 'Response')

    # Get all responses that have a guardian but no user
    responses_to_update = Response.objects.filter(guardian__isnull=False, user__isnull=True)

    for response in responses_to_update:
        # Set user to guardian's user account
        response.user = response.guardian.user
        response.save(update_fields=['user'])

    print(f"Migrated {responses_to_update.count()} responses from guardian to user")


def reverse_migration(apps, schema_editor):
    """
    Reverse migration - not critical since we're keeping both fields temporarily
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_remove_response_survey_resp_templat_9bed15_idx_and_more'),
        ('core', '0003_alter_schoolclass_section'),  # Ensure Guardian model is available
    ]

    operations = [
        migrations.RunPython(migrate_guardian_to_user, reverse_migration),
    ]
