# Generated by Django 4.2.7 on 2025-08-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0003_alter_template_default_frequency_response_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="response",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "رد نموذج البلاغ",
                "verbose_name_plural": "ردود نماذج البلاغات",
            },
        ),
        migrations.AddIndex(
            model_name="response",
            index=models.Index(
                fields=["template", "guardian", "-created_at"],
                name="survey_resp_templat_9bed15_idx",
            ),
        ),
    ]
