# Generated by Django 5.2.6 on 2025-11-09 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_schoolclass_section'),
        ('survey', '0004_migrate_guardian_to_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ الانتهاء (الموعد النهائي)')),
                ('is_active', models.BooleanField(default=True, help_text='فترة واحدة فقط يمكن أن تكون نشطة لكل استطلاع', verbose_name='نشط؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_periods', to='core.school', verbose_name='المدرسة')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_survey_periods', to=settings.AUTH_USER_MODEL, verbose_name='أرسل بواسطة')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='survey.template', verbose_name='الاستطلاع')),
            ],
            options={
                'verbose_name': 'فترة استطلاع',
                'verbose_name_plural': 'فترات الاستطلاعات',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='SurveyDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='تم الإكمال؟')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإكمال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('response', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distribution', to='survey.response', verbose_name='الرد')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_distributions', to='core.school', verbose_name='المدرسة')),
                ('student', models.ForeignKey(blank=True, help_text='الطالب المعني (فقط لاستطلاعات أولياء الأمور)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_distributions', to='core.student', verbose_name='الطالب')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='survey.template', verbose_name='الاستطلاع')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_distributions', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='survey.surveyperiod', verbose_name='الفترة')),
            ],
            options={
                'verbose_name': 'توزيع استطلاع',
                'verbose_name_plural': 'توزيعات الاستطلاعات',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddIndex(
            model_name='surveyperiod',
            index=models.Index(fields=['survey', 'is_active'], name='survey_surv_survey__02a27e_idx'),
        ),
        migrations.AddIndex(
            model_name='surveyperiod',
            index=models.Index(fields=['school', 'is_active'], name='survey_surv_school__d5ef62_idx'),
        ),
        migrations.AddIndex(
            model_name='surveyperiod',
            index=models.Index(fields=['-start_date'], name='survey_surv_start_d_36612d_idx'),
        ),
        migrations.AddIndex(
            model_name='surveydistribution',
            index=models.Index(fields=['user', 'is_completed'], name='survey_surv_user_id_41bd00_idx'),
        ),
        migrations.AddIndex(
            model_name='surveydistribution',
            index=models.Index(fields=['period', 'user'], name='survey_surv_period__eaf62e_idx'),
        ),
        migrations.AddIndex(
            model_name='surveydistribution',
            index=models.Index(fields=['school', 'user'], name='survey_surv_school__0156d1_idx'),
        ),
        migrations.AddIndex(
            model_name='surveydistribution',
            index=models.Index(fields=['school', 'is_completed'], name='survey_surv_school__135c1e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='surveydistribution',
            unique_together={('period', 'user', 'student')},
        ),
    ]
