# Generated by Django 4.2.7 on 2025-08-23 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_guardian_selected_student"),
        ("survey", "0004_alter_response_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="response",
            name="student",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responses",
                to="core.student",
                verbose_name="الطالب",
            ),
            preserve_default=False,
        ),
    ]
